#! /usr/bin/env python
# encoding: utf-8

from waflib import Utils
import os

top = '.'
PROJECT_NAME = 'slsutils'
def options(opt):
	return
def configure(conf):
	return
def build(ctx):
    source = ctx.path.ant_glob('*.c')
    defines = ['_DEFAULT_SOURCE', 'VERSION=\"1.1"', 'XINERAMA']
    includes = ['.', 'PCTL']
    cflags = ['-std=c99', '-pedantic', '-Wall', '-Wno-deprecated-declarations', '-Os', '-Wno-unused-parameter', '-Wextra']
    libs = ['PCTL',]
    ctx.stlib(
		source   = source,
		target   = PROJECT_NAME,
		name     = PROJECT_NAME,
		features = 'c',
		includes = includes,
		cflags = cflags,
		defines  = defines,
		use      = libs,
		# idx      = bld.get_taskgen_count()
	)
