#! /usr/bin/env python
# encoding: utf-8

from waflib import Utils
import os

top = '.'
PROJECT_NAME = 'dwm'
install_path="/usr/local/bin"
def options(opt):
	return
def configure(conf):
	return
def build(ctx):
	source = ['drw.c',
			'dwm.c',
			'util.c']
	includes = ['.', '/usr/include/freetype2']
	libs = ['X11', 'FTCFG', 'XFT', 'XINER', 'GLEW']
	defines = ['_DEFAULT_SOURCE', '_BSD_SOURCE', '_XOPEN_SOURCE=700L', 'VERSION=\"6.5"', 'XINERAMA']
	cflags = ['-std=c99', '-pedantic', '-Wall', '-Wno-deprecated-declarations', '-Os']
	ctx.install_as(
		dest="/usr/local/share/dwm/background.png",
		srcfile="background.png",
		)
	ctx.install_as(
		dest="/usr/local/share/dwm/wallpaper.glsl",
		srcfile="wallpaper.glsl",
		)
	ctx.program(
		source   = source,
		target   = PROJECT_NAME,
		name     = PROJECT_NAME,
		features = 'c',
		includes = includes,
		cflags = cflags,
		defines  = defines,
		use      = libs,
		install_path = install_path,
		# idx      = bld.get_taskgen_count()
	)
